/* app */
export const APP_CHANGE_VALUE = 'APP_CHANGE_VALUE'

/* cadastro */
export const SIGN_UP_CHANGE_NAME = 'SIGN_UP_CHANGE_NAME'
export const SIGN_UP_CHANGE_EMAIL = 'SIGN_UP_CHANGE_EMAIL'
export const SIGN_UP_CHANGE_PHONE = 'SIGN_UP_CHANGE_PHONE'
export const SIGN_UP_CHANGE_PASSWORD = 'SIGN_UP_CHANGE_PASSWORD'
export const SIGN_UP_CHANGE_SHOWDIALOG = 'SIGN_UP_CHANGE_SHOWDIALOG'

/* login */
export const SIGN_IN_CHANGE_VALUE = 'SIGN_IN_CHANGE_VALUE'
export const SIGN_IN_CLEAN = 'SIGN_IN_CLEAN'

/* storage */
export const STORAGE_CHANGE_VALUE = 'STORAGE_CHANGE_VALUE'
export const STORAGE_CHANGE_CHILD_VALUE = 'STORAGE_CHANGE_CHILD_VALUE'
export const STORAGE_CHANGE_USERDATA_CHILD_VALUE = "STORAGE_CHANGE_USERDATA_CHILD_VALUE"

/* user */
export const USER_CHANGE_VALUE = 'USER_CHANGE_VALUE'
export const USERS_CHANGE_VALUE = 'USERS_CHANGE_VALUE'
export const USERS_CHANGE_CHILD_VALUE = 'USERS_CHANGE_CHILD_VALUE'
export const USERS_CHANGE_USERDATA_CHILD_VALUE = "USERS_CHANGE_USERDATA_CHILD_VALUE"
